Use GPL-2.0-or-later instead of Ruby and BSDL2
ruby/gdbm pull request #11
Opened 2022-01-04 07:54 UTC by hsbt

Fixes https://github.com/ruby/gdbm/issues/8

2022-01-04 07:56 UTC, hsbt commented
@shyouhei Can you look this?

2022-01-04 08:06 UTC, shyouhei requested changes
This part is great! 👍  I guess you might also want to change `LICENSE.txt`.

2022-01-04 08:34 UTC, hsbt commented
> I guess you might also want to change `LICENSE.txt`.

Oh, I missed that. I did update it at https://github.com/ruby/gdbm/pull/11/commits/15251b84e77000c101627f2be6e5123bac7a918e

2022-01-05 00:37 UTC, shyouhei approved these changes

2022-01-05 01:08 UTC, merged